import { chromium } from "playwright-core";
const b = await chromium.launch({ executablePath: "/usr/local/bin/google-chrome", args: ["--no-sandbox"] });
const p = await b.newPage({ viewport: { width: 1340, height: 900 } });
const errs = [];
p.on("console", (m) => m.type() === "error" && errs.push(m.text()));
await p.goto("http://127.0.0.1:43127/");
const demo = p.getByRole("button", { name: /صاحب المصنع/ });
if (await demo.count()) await demo.first().click();
await p.goto("http://127.0.0.1:43127/returns");
await p.waitForTimeout(1000);
await p.getByRole("button", { name: /التكلفة والإثبات/ }).first().click();
const panel = p.locator("div.fixed.inset-0.z-50");
await p.waitForTimeout(600);
const before = await panel.locator("img").count();
await panel.locator('input[type="file"]').setInputFiles("/opt/cursor/artifacts/screenshots/topbar_390.png");
await p.waitForTimeout(2500);
const after = await panel.locator("img").count();
console.log("صور قبل:", before, "وبعد:", after);
console.log("نص زر الرفع:", (await panel.locator("label", { hasText: "اختار صورة من الجهاز" }).count()) ? "عربي ✓" : "مش موجود ✗");
console.log("أخطاء الكونسول:", errs.length ? errs.join(" | ") : "مافيش");
await b.close();
