import { chromium } from "playwright-core";
const BASE = "http://127.0.0.1:43127";
const browser = await chromium.launch({ executablePath: "/usr/local/bin/google-chrome" });
const page = await browser.newPage({ viewport: { width: 1200, height: 1100 } });
const logs = [];
page.on("pageerror", (e) => logs.push(e.message));
page.on("console", (m) => m.type() === "error" && logs.push(m.text()));
await page.goto(BASE, { waitUntil: "networkidle" });
await page.evaluate(() => localStorage.clear());
await page.reload({ waitUntil: "networkidle" });
await page.getByRole("button", { name: /صاحب المصنع/ }).first().click();
await page.waitForTimeout(800);
await page.goto(`${BASE}/returns`, { waitUntil: "networkidle" });
await page.waitForTimeout(600);
const card = page.locator("main div.bg-card").filter({ hasText: "RET-2026-000002" }).last();
console.log("زر تتبّع الباندل:", await card.getByRole("link", { name: /تتبّع الباندل/ }).count());
await card.getByRole("link", { name: /تتبّع الباندل/ }).first().click();
await page.waitForTimeout(900);
console.log("العنوان:", page.url().replace(BASE, ""));
console.log((await page.locator("main").innerText()).split("\n").filter((x) => x.trim()).slice(0, 26).join("\n"));
console.log("\nأخطاء:", logs.length ? logs.join("\n") : "مافيش");
await browser.close();
